import os, time
print("Hello...and goodbye!")
time.sleep(2)
os.system("clear")
print("Welcome to twisted agencies")
time.sleep(2)
os.system("clear")
print("I'm your host today, Mr.Benard")
time.sleep(3)
os.system("clear")
print("But don't go around setting your expectations too high...")
time.sleep(3)
os.system("clear")
print("Coz all of us here are twisted...")
time.sleep(3)
print("Screen off in")
print("3")
time.sleep(1)
print("2")
time.sleep(1)
print("1...")
time.sleep(1)
os.system("clear")