print("""Hello! Welcome and for today , we would like to know you more...if you don't mind that is😁""")
mind = input("Do you mind?")
name = input("What's your name?:")
print("Wow! That's a cool name you got there!")
eyecolour = input("What's your eye colour?:")
print("Too common😂")
food = input("What's your favourite meal?:")
print()
print("So you're" , name, "with " , eyecolour, "eyes and you're probably hungry for" , food, "right now." )
input("Is that correct?")
print("")
print("Thank you for your time and have a nice day!")